/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSshKeysRouteImport } from './routes/_app/ssh-keys'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminConfigRouteImport } from './routes/_app/admin/config'
import { Route as AppAdminCustomersRouteImport } from './routes/_app/admin/customers'
import { Route as AppAdminVpsRouteImport } from './routes/_app/admin/vps'
import { Route as AppVpsIndexRouteImport } from './routes/_app/vps/index'
import { Route as AppVpsIdRouteImport } from './routes/_app/vps/$id'
import { Route as AppVpsNewRouteImport } from './routes/_app/vps/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSshKeysRoute = AppSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfigRoute = AppAdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCustomersRoute = AppAdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminVpsRoute = AppAdminVpsRouteImport.update({
  id: '/admin/vps',
  path: '/admin/vps',
  getParentRoute: () => AppRoute,
} as any)
const AppVpsIndexRoute = AppVpsIndexRouteImport.update({
  id: '/vps/',
  path: '/vps/',
  getParentRoute: () => AppRoute,
} as any)
const AppVpsIdRoute = AppVpsIdRouteImport.update({
  id: '/vps/$id',
  path: '/vps/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVpsNewRoute = AppVpsNewRouteImport.update({
  id: '/vps/new',
  path: '/vps/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/ssh-keys': typeof AppSshKeysRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/config': typeof AppAdminConfigRoute
  '/admin/customers': typeof AppAdminCustomersRoute
  '/admin/vps': typeof AppAdminVpsRoute
  '/vps/$id': typeof AppVpsIdRoute
  '/vps/new': typeof AppVpsNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/vps/': typeof AppVpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/ssh-keys': typeof AppSshKeysRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/config': typeof AppAdminConfigRoute
  '/admin/customers': typeof AppAdminCustomersRoute
  '/admin/vps': typeof AppAdminVpsRoute
  '/vps/$id': typeof AppVpsIdRoute
  '/vps/new': typeof AppVpsNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/vps': typeof AppVpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ssh-keys': typeof AppSshKeysRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/config': typeof AppAdminConfigRoute
  '/_app/admin/customers': typeof AppAdminCustomersRoute
  '/_app/admin/vps': typeof AppAdminVpsRoute
  '/_app/vps/$id': typeof AppVpsIdRoute
  '/_app/vps/new': typeof AppVpsNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/vps/': typeof AppVpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/account'
    | '/activity'
    | '/dashboard'
    | '/ssh-keys'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/customers'
    | '/admin/vps'
    | '/vps/$id'
    | '/vps/new'
    | '/admin/'
    | '/vps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/account'
    | '/activity'
    | '/dashboard'
    | '/ssh-keys'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/customers'
    | '/admin/vps'
    | '/vps/$id'
    | '/vps/new'
    | '/admin'
    | '/vps'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/setup'
    | '/_app/account'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/ssh-keys'
    | '/_app/admin/audit'
    | '/_app/admin/config'
    | '/_app/admin/customers'
    | '/_app/admin/vps'
    | '/_app/vps/$id'
    | '/_app/vps/new'
    | '/_app/admin/'
    | '/_app/vps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ssh-keys': {
      id: '/_app/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/ssh-keys'
      preLoaderRoute: typeof AppSshKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/config': {
      id: '/_app/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AppAdminConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/customers': {
      id: '/_app/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AppAdminCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/vps': {
      id: '/_app/admin/vps'
      path: '/admin/vps'
      fullPath: '/admin/vps'
      preLoaderRoute: typeof AppAdminVpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vps/': {
      id: '/_app/vps/'
      path: '/vps'
      fullPath: '/vps/'
      preLoaderRoute: typeof AppVpsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vps/$id': {
      id: '/_app/vps/$id'
      path: '/vps/$id'
      fullPath: '/vps/$id'
      preLoaderRoute: typeof AppVpsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vps/new': {
      id: '/_app/vps/new'
      path: '/vps/new'
      fullPath: '/vps/new'
      preLoaderRoute: typeof AppVpsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSshKeysRoute: typeof AppSshKeysRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminConfigRoute: typeof AppAdminConfigRoute
  AppAdminCustomersRoute: typeof AppAdminCustomersRoute
  AppAdminVpsRoute: typeof AppAdminVpsRoute
  AppVpsIdRoute: typeof AppVpsIdRoute
  AppVpsNewRoute: typeof AppVpsNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppVpsIndexRoute: typeof AppVpsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSshKeysRoute: AppSshKeysRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminConfigRoute: AppAdminConfigRoute,
  AppAdminCustomersRoute: AppAdminCustomersRoute,
  AppAdminVpsRoute: AppAdminVpsRoute,
  AppVpsIdRoute: AppVpsIdRoute,
  AppVpsNewRoute: AppVpsNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppVpsIndexRoute: AppVpsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
